### ISSUE TITLE
Why react_native_mqtt has been directed to this?

### ISSUE THREAD

**Issue by pewh** [Introvertuous/react-native-mqtt#10]
Hello,

My use case is use native library of mqtt, and previously https://github.com/Introvertuous/react_native_mqtt is suit for me. And now I'm wondering why it has been directed to JS version?

AFAIK, MQTT with tcp is more efficient & reliable than websocket. CMIIW.

**Comment by Introvertuous** [comment]
This was just a name change from react_native_mqtt to react-native-mqtt (github only), this library has always been a wrapper around the PAHO mqtt client library. 

I agree that using tcp would certainly be better, but I do not have the time nor the interest in react native to implement a native interface for android and iOS.

**Comment by Introvertuous** [comment]
btw I did open an issue a while ago that mentions this: #2
