### ISSUE TITLE
android mqtts connect failed

### ISSUE THREAD

**Issue by h124551753** [Introvertuous/react-native-mqtt#8]
I use mqtts to connect broker, and set 'useSSL: true'; it works well  with ios platform, but it not working with android.
throw exception:
'{invocationContext: undefined, errorCode: 7, errorMessage: "AMQJS0007E Socket error:undefined."}'

**Comment by Introvertuous** [comment]
This is an error on the side of the broker, not in paho or this wrapper.
I assume you are using the broker in the example: ""

Here is a list of brokers, you will need to select a broker / port that supports ssl:
https://github.com/mqtt/mqtt.github.io/wiki/public_brokers

I will update the example to use a broker / port that supports both ssl and ws.
